import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import WalletContext from '../contexts/walletContext'
import { TabProvider } from '@/contexts/navbarContext'

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html
			lang="en"
			className={`${inter.variable}`}
		>
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=Trade+Winds&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body>
				<WalletContext>
					<TabProvider>{children}</TabProvider>
				</WalletContext>
			</body>
		</html>
	)
}
